name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Commit and push changes to settings.json
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/settings.json
          git commit -m "Update settings.json"
          git push
        continue-on-error: true  # Continue even if there's no change to commit

      - name: Set up GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Ensure this path matches where your JSON file is located

      - name: Verify deployment
        run: |
          echo "Deployment successful!"
